const CREATE_ITEM = 'CREATE_ITEM';
const EDIT_ITEM = 'EDIT_ITEM';
const DELETE_ITEM = 'DELETE_ITEM';
const RESTORE_ITEM = 'RESTORE_ITEM'; 
const MARK_COMPLETE = 'MARK_COMPLETE';
const MARK_INCOMPLETE = 'MARK_INCOMPLETE';

export default {
  CREATE_ITEM,
  EDIT_ITEM,
  DELETE_ITEM,
  RESTORE_ITEM,
  MARK_COMPLETE,
  MARK_INCOMPLETE,
};